### ISSUE TITLE
bug when editing saved Posts

### ISSUE THREAD

**Issue by rustyflakes** [thepostcode/nextpost#2] opened 2017-04-04 02:47 UTC
When in Saved posts page, 
If I click the Pencil Icon of any post in order to schedule it or post it in the /post page. Here are the bugs I've encountered per device:

- Desktop: Preview text doesn't load.
- iPad: Preview photo and Text doesn't load.
- iPhone: Preview photo and Text doesn't load.

**Comment by thepostcode** [comment] 2017-04-04 09:59
I checked in demo version (http://demo.thepostcode.co/nextpost/), it loads preview photo and caption text as intended. Make sure that you've not edited any files.

**Closed** 2017-04-05 10:51 UTC
Labels: fixed
